# Análisis de la temperatura

## Bibliotecas

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
pathFile="C:\\Users\\User\\Downloads\\Datos_Hidrometeorol_gicos_Crudos_-_Red_de_Estaciones_IDEAM___Temperatura_20250129.csv"
df = pd.read_csv(pathFile)
print(df)

          CodigoEstacion  CodigoSensor        FechaObservacion  \
0               29045000            68  08/01/2015 03:00:00 PM
1               21055501            68  06/23/2019 02:15:00 PM
2               35035130            68  07/09/2015 02:00:00 AM
3               21205502            68  11/22/2018 06:20:00 AM
4               26065502            68  06/09/2016 05:40:00 AM
...                  ...           ...                     ...
81764747        35085080            68  04/13/2017 12:00:00 PM
81764748        29065501            68  11/20/2018 06:05:00 AM
81764749        21206950            68  06/21/2007 06:00:00 PM
81764750        52025501            68  04/13/2019 04:05:00 AM
81764751        23065501            68  09/17/2016 07:45:00 AM

          ValorObservado             NombreEstacion  Departamento  \
0               35.50000        SABANALARGA TX GPRS     ATLÁNTICO
1               20.58631        SIMON CAMPOS  - AUT         HUILA
2                4.20000     PARAMO CHINGAZA  - AUT  CUNDINAMARCA
3               18.52375            MISIONES  - AUT  CUNDINAMARCA
4               15.90000         TRINIDAD LA  - AUT         CAUCA
...                  ...                        ...           ...
81764747        22.40000           LA CAPILLA - AUT        BOYACÁ
81764748        20.28031          CIENAGA,LA  - AUT     MAGDALENA
81764749         8.80000  PARAMO GUACHENEQUE  - AUT  CUNDINAMARCA
81764750        16.86341             LA VEGA  - AUT         CAUCA
81764751        20.10000               PACHO  - AUT  CUNDINAMARCA

            Municipio ZonaHidrografica    Latitud   Longitud  \
0         SABANALARGA   BAJO MAGDALENA  10.637000 -74.919000
1            LA PLATA   ALTO MAGDALENA   2.345831 -75.878056
2              GUASCA             META   4.713667 -73.803250
3          EL COLEGIO   ALTO MAGDALENA   4.544997 -74.440556
4            PIENDAMÓ            CAUCA   2.750556 -76.579167
...               ...              ...        ...        ...
81764747   LA CAPILLA             META   5.099194 -73.436000
81764748      CIÉNAGA   BAJO MAGDALENA  10.897858 -74.081567
81764749  VILLAPINZÓN   ALTO MAGDALENA   5.236056 -73.525083
81764750      LA VEGA            PATÍA   2.092942 -76.812028
81764751        PACHO  MEDIO MAGDALENA   5.129128 -74.157697

         DescripcionSensor UnidadMedida
0            Temp Aire 2 m           °C
1            Temp Aire 2 m           °C
2            Temp Aire 2 m           °C
3            Temp Aire 2 m           °C
4            Temp Aire 2 m           °C
...                    ...          ...
81764747     Temp Aire 2 m           °C
81764748     Temp Aire 2 m           °C
81764749     Temp Aire 2 m           °C
81764750     Temp Aire 2 m           °C
81764751     Temp Aire 2 m           °C

[81764752 rows x 12 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81764752 entries, 0 to 81764751
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   CodigoEstacion     int64
 1   CodigoSensor       int64
 2   FechaObservacion   object
 3   ValorObservado     float64
 4   NombreEstacion     object
 5   Departamento       object
 6   Municipio          object
 7   ZonaHidrografica   object
 8   Latitud            float64
 9   Longitud           float64
 10  DescripcionSensor  object
 11  UnidadMedida       object
dtypes: float64(3), int64(2), object(7)
memory usage: 7.3+ GB

In [5]:
departamentos=df['Departamento'].unique()
print(departamentos)

['ATLÁNTICO' 'HUILA' 'CUNDINAMARCA' 'CAUCA' 'META' 'BOYACÁ'
 'VALLE DEL CAUCA' 'CESAR' 'BOGOTA D.C.' 'MAGDALENA' 'TOLIMA' 'CALDAS'
 'NORTE DE SANTANDER' 'CHOCÓ' 'NARIÑO' 'ANTIOQUIA' 'RISARALDA' 'PUTUMAYO'
 'BOGOTA' 'SANTANDER' 'SUCRE' 'CHOCO' 'BOLIVAR' 'CASANARE' 'BOLÍVAR'
 'QUINDÍO' 'ATLANTICO' 'CÓRDOBA' 'CAQUETA' 'LA GUAJIRA' 'CORDOBA'
 'AMAZONAS' 'NARINO' 'GUAINÍA' 'ARAUCA' 'SAN ANDRÉS PROVIDENCIA'
 'GUAVIARE' '<nil>' 'VAUPÉS' 'VICHADA'
 'ARCHIPIELAGO DE SAN ANDRES, PROVIDENCIA Y SANTA CATALINA' 'BOGOTÁ'
 'ARCHIPIÉLAGO DE SAN ANDRES PROVIDENCIA Y SANTA CATALINA' 'CAQUETÁ'
 'ARCHIPIELAGO DE SAN ANDRES PROVIDENCIA Y SANTA CATALINA']

## Datos del Magdalena

In [3]:
datosMagdalena= df[df['Departamento']=='MAGDALENA']
print(datosMagdalena)

          CodigoEstacion  CodigoSensor        FechaObservacion  \
15              29065501            68  06/27/2017 11:10:00 AM
19              29065130            68  06/29/2017 05:00:00 PM
25              29065130            68  02/18/2015 10:00:00 AM
63              29065130            68  07/12/2010 08:00:00 AM
155             15015120            68  09/15/2018 09:00:00 PM
...                  ...           ...                     ...
81764522        29065000            68  08/15/2019 05:00:00 PM
81764675        29065000            68  10/02/2017 04:00:00 AM
81764692        29065120            68  03/09/2010 03:00:00 PM
81764731        29065501            68  12/21/2017 09:15:00 AM
81764748        29065501            68  11/20/2018 06:05:00 AM

          ValorObservado                  NombreEstacion Departamento  \
15              22.58378               CIENAGA,LA  - AUT    MAGDALENA
19              28.40000               LA GRAN VIA - AUT    MAGDALENA
25              31.10000               LA GRAN VIA - AUT    MAGDALENA
63              27.60000               LA GRAN VIA - AUT    MAGDALENA
155             26.00000  UNIVERSIDAD TECNOLOGICA  - AUT    MAGDALENA
...                  ...                             ...          ...
81764522        24.20000                MEDIA LUNA - AUT    MAGDALENA
81764675        25.00000                MEDIA LUNA - AUT    MAGDALENA
81764692        24.60000            BATALLON NO. 6 - AUT    MAGDALENA
81764731        26.62027               CIENAGA,LA  - AUT    MAGDALENA
81764748        20.28031               CIENAGA,LA  - AUT    MAGDALENA

              Municipio  ZonaHidrografica    Latitud   Longitud  \
15              CIÉNAGA    BAJO MAGDALENA  10.897858 -74.081567
19        ZONA BANANERA    BAJO MAGDALENA  10.850000 -74.133333
25        ZONA BANANERA    BAJO MAGDALENA  10.850000 -74.133333
63        ZONA BANANERA    BAJO MAGDALENA  10.850000 -74.133333
155         SANTA MARTA  CARIBE - GUAJIRA  11.223056 -74.185917
...                 ...               ...        ...        ...
81764522        PIVIJAI    BAJO MAGDALENA  10.510028 -74.506667
81764675        PIVIJAI    BAJO MAGDALENA  10.510028 -74.506667
81764692      FUNDACIÓN    BAJO MAGDALENA  10.465361 -73.927778
81764731        CIÉNAGA    BAJO MAGDALENA  10.897858 -74.081567
81764748        CIÉNAGA    BAJO MAGDALENA  10.897858 -74.081567

         DescripcionSensor UnidadMedida
15           Temp Aire 2 m           °C
19           Temp Aire 2 m           °C
25           Temp Aire 2 m           °C
63           Temp Aire 2 m           °C
155          Temp Aire 2 m           °C
...                    ...          ...
81764522     Temp Aire 2 m           °C
81764675     Temp Aire 2 m           °C
81764692     Temp Aire 2 m           °C
81764731     Temp Aire 2 m           °C
81764748     Temp Aire 2 m           °C

[1116893 rows x 12 columns]

In [9]:
fechasObservacionesMagdalena=datosMagdalena['FechaObservacion'].unique()
print(fechasObservacionesMagdalena)

nombreEstacionesMagdalena=datosMagdalena['NombreEstacion'].unique()
print(nombreEstacionesMagdalena)

['06/27/2017 11:10:00 AM' '06/29/2017 05:00:00 PM'
 '02/18/2015 10:00:00 AM' ... '09/26/2006 08:00:00 AM'
 '12/21/2017 09:15:00 AM' '11/20/2018 06:05:00 AM']
['CIENAGA,LA  - AUT' 'LA GRAN VIA - AUT' 'UNIVERSIDAD TECNOLOGICA  - AUT'
 'EL DIFICIL - AUT' 'MEDIA LUNA - AUT' 'AEROPUERTO LAS FLORES  - AUT'
 'BATALLON NO. 6 - AUT' 'LOS ALAMOS' 'COLEGIO KANKAWARWA'
 'SAN ISIDRO BONDA - AUT' 'PALMOR - SIERRA NEVADA - AUT'
 'SAN LORENZO  - AUT' 'GUACHACA - AUT' 'PARQUE TAYRONA'
 'AEROPUERTO SIMON BOLIVAR' 'UNIVERSIDAD TECNOLOGICA'
 'AEROPUERTO LAS FLORES' 'MEDIA LUNA' 'LA GRAN VIA' 'BATALLON NO. 6']

## Datos estación Ciénaga

In [34]:
datoCienaga=datosMagdalena[(datosMagdalena['NombreEstacion']=='CIENAGA,LA  - AUT')]
print(datoCienaga)

          CodigoEstacion  CodigoSensor        FechaObservacion  \
15              29065501            68  06/27/2017 11:10:00 AM
281             29065501            68  10/27/2018 09:25:00 AM
584             29065501            68  03/07/2019 06:00:00 AM
813             29065501            68  03/12/2018 02:35:00 PM
866             29065501            68  10/28/2017 02:55:00 AM
...                  ...           ...                     ...
81763940        29065501            68  05/24/2019 12:50:00 PM
81764054        29065501            68  10/24/2017 09:20:00 PM
81764134        29065501            68  10/30/2017 05:20:00 AM
81764731        29065501            68  12/21/2017 09:15:00 AM
81764748        29065501            68  11/20/2018 06:05:00 AM

          ValorObservado     NombreEstacion Departamento Municipio  \
15              22.58378  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
281             22.94454  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
584             20.80172  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
813             31.40992  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
866             20.61759  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
...                  ...                ...          ...       ...
81763940        23.20323  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
81764054        19.33218  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
81764134        17.79400  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
81764731        26.62027  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA
81764748        20.28031  CIENAGA,LA  - AUT    MAGDALENA   CIÉNAGA

         ZonaHidrografica    Latitud   Longitud DescripcionSensor UnidadMedida
15         BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
281        BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
584        BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
813        BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
866        BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
...                   ...        ...        ...               ...          ...
81763940   BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
81764054   BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
81764134   BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
81764731   BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C
81764748   BAJO MAGDALENA  10.897858 -74.081567     Temp Aire 2 m           °C

[282793 rows x 12 columns]

In [35]:
display(datoCienaga)

,CodigoEstacion,CodigoSensor,FechaObservacion,ValorObservado,NombreEstacion,Departamento,Municipio,ZonaHidrografica,Latitud,Longitud,DescripcionSensor,UnidadMedida
15,29065501,68,06/27/2017 11:10:00 AM,22.58378,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
281,29065501,68,10/27/2018 09:25:00 AM,22.94454,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
584,29065501,68,03/07/2019 06:00:00 AM,20.80172,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
813,29065501,68,03/12/2018 02:35:00 PM,31.40992,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
866,29065501,68,10/28/2017 02:55:00 AM,20.61759,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
...,...,...,...,...,...,...,...,...,...,...,...,...
81763940,29065501,68,05/24/2019 12:50:00 PM,23.20323,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
81764054,29065501,68,10/24/2017 09:20:00 PM,19.33218,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
81764134,29065501,68,10/30/2017 05:20:00 AM,17.79400,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
81764731,29065501,68,12/21/2017 09:15:00 AM,26.62027,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C
81764748,29065501,68,11/20/2018 06:05:00 AM,20.28031,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C

In [22]:

FechaObservacionZonaEstudio=datoCienaga['FechaObservacion'].unique()
print(FechaObservacionZonaEstudio)

['06/27/2017 11:10:00 AM' '10/27/2018 09:25:00 AM'
 '03/07/2019 06:00:00 AM' ... '10/30/2017 05:20:00 AM'
 '12/21/2017 09:15:00 AM' '11/20/2018 06:05:00 AM']

## Gráficos Estación Ciénaga

In [36]:
#datosanio2017=datosMagdalena[(datosMagdalena['FechaObservacion']=='CIENAGA,LA  - AUT')]
new_datos_Cienaga = datoCienaga.assign(Fecha=0)

In [37]:
display(new_datos_Cienaga)

,CodigoEstacion,CodigoSensor,FechaObservacion,ValorObservado,NombreEstacion,Departamento,Municipio,ZonaHidrografica,Latitud,Longitud,DescripcionSensor,UnidadMedida,Fecha
15,29065501,68,06/27/2017 11:10:00 AM,22.58378,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
281,29065501,68,10/27/2018 09:25:00 AM,22.94454,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
584,29065501,68,03/07/2019 06:00:00 AM,20.80172,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
813,29065501,68,03/12/2018 02:35:00 PM,31.40992,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
866,29065501,68,10/28/2017 02:55:00 AM,20.61759,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81763940,29065501,68,05/24/2019 12:50:00 PM,23.20323,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764054,29065501,68,10/24/2017 09:20:00 PM,19.33218,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764134,29065501,68,10/30/2017 05:20:00 AM,17.79400,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764731,29065501,68,12/21/2017 09:15:00 AM,26.62027,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764748,29065501,68,11/20/2018 06:05:00 AM,20.28031,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0

In [49]:
display(new_datos_Cienaga)

,CodigoEstacion,CodigoSensor,FechaObservacion,ValorObservado,NombreEstacion,Departamento,Municipio,ZonaHidrografica,Latitud,Longitud,DescripcionSensor,UnidadMedida,Fecha
15,29065501,68,06/27/2017 11:10:00 AM,22.58378,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
281,29065501,68,10/27/2018 09:25:00 AM,22.94454,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
584,29065501,68,03/07/2019 06:00:00 AM,20.80172,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
813,29065501,68,03/12/2018 02:35:00 PM,31.40992,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
866,29065501,68,10/28/2017 02:55:00 AM,20.61759,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81763940,29065501,68,05/24/2019 12:50:00 PM,23.20323,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764054,29065501,68,10/24/2017 09:20:00 PM,19.33218,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764134,29065501,68,10/30/2017 05:20:00 AM,17.79400,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764731,29065501,68,12/21/2017 09:15:00 AM,26.62027,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0
81764748,29065501,68,11/20/2018 06:05:00 AM,20.28031,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,0

In [ ]:
from datetime import datetime as dt
datoCienaga['Fecha']=[ dt.strptime(s,'%m/%d/%Y %H:%M:%S %p').strftime('%d/%m/%Y')  for s in  datoCienaga['FechaObservacion']]

C:\Users\User\AppData\Local\Temp\ipykernel_14428\4018417381.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datoCienaga['Fecha']=[ dt.strptime(s,'%m/%d/%Y %H:%M:%S %p').strftime('%d/%m/%Y')  for s in  datoCienaga['FechaObservacion']]

In [56]:
display(datoCienaga)

,CodigoEstacion,CodigoSensor,FechaObservacion,ValorObservado,NombreEstacion,Departamento,Municipio,ZonaHidrografica,Latitud,Longitud,DescripcionSensor,UnidadMedida,Fecha
15,29065501,68,06/27/2017 11:10:00 AM,22.58378,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,27/06/2017
281,29065501,68,10/27/2018 09:25:00 AM,22.94454,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,27/10/2018
584,29065501,68,03/07/2019 06:00:00 AM,20.80172,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,07/03/2019
813,29065501,68,03/12/2018 02:35:00 PM,31.40992,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,12/03/2018
866,29065501,68,10/28/2017 02:55:00 AM,20.61759,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,28/10/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81763940,29065501,68,05/24/2019 12:50:00 PM,23.20323,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,24/05/2019
81764054,29065501,68,10/24/2017 09:20:00 PM,19.33218,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,24/10/2017
81764134,29065501,68,10/30/2017 05:20:00 AM,17.79400,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,30/10/2017
81764731,29065501,68,12/21/2017 09:15:00 AM,26.62027,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,21/12/2017
81764748,29065501,68,11/20/2018 06:05:00 AM,20.28031,"CIENAGA,LA - AUT",MAGDALENA,CIÉNAGA,BAJO MAGDALENA,10.897858,-74.081567,Temp Aire 2 m,°C,20/11/2018