## Control de Asistencia

## Matriculados

In [1]:
import pandas as pd
import re

matriculados= pd.read_excel("C:\\Users\\User\\Downloads\\ControlAsistencia\\Viernes\\Matriculados.xlsx") 
matriculados['NombreSinEspacios']=(matriculados['Nombre'].str.replace(" ",""))
display(matriculados)

,No.,Código,Nombre,Firma,NombreSinEspacios
0,1,2021115080,MAICOL GUILLERMO ASCANIO SILVA,NaN,MAICOLGUILLERMOASCANIOSILVA
1,2,2023115017,LUIS MIGUEL BECERRA DIAZ,NaN,LUISMIGUELBECERRADIAZ
2,3,2021215117,ANDY YULIETH BOLANO SILVA,NaN,ANDYYULIETHBOLANOSILVA
3,4,2022215042,DANIELA MARSELA BOLANO TORRES,NaN,DANIELAMARSELABOLANOTORRES
4,5,2023115018,SAMUEL DAVID GUERRA VEGA,NaN,SAMUELDAVIDGUERRAVEGA
5,6,2023115044,JORGE ANDRES LARA AGUILAR,NaN,JORGEANDRESLARAAGUILAR
6,8,2023115005,NATALIA MARIA MACHADO MARTINEZ,NaN,NATALIAMARIAMACHADOMARTINEZ
7,9,2023215111,ANA VANESSA MADRID PEREZ,NaN,ANAVANESSAMADRIDPEREZ
8,10,2023115002,SERGIO ANDRES MORALES MERCADO,NaN,SERGIOANDRESMORALESMERCADO
9,11,2023215077,FAIRUZ TATIANA NUNEZ BENAVIDES,NaN,FAIRUZTATIANANUNEZBENAVIDES
10,12,2022115056,KALETH RAFAEL PACHECO GARCIA,NaN,KALETHRAFAELPACHECOGARCIA
11,13,2023115015,VICTOR HUGO PATINO ZAMBRANO,NaN,VICTORHUGOPATINOZAMBRANO
12,14,2020111020,JAIR ALBERTO REYES ELIAS,NaN,JAIRALBERTOREYESELIAS
13,15,2023115041,JUAN JOSE RIVERA MERCHAN,NaN,JUANJOSERIVERAMERCHAN
14,16,2023115009,LORENZO RAFAEL ROMERO FONSECA,NaN,LORENZORAFAELROMEROFONSECA
15,17,2023115010,JUAN GUILLERMO RUIZ GUISAO,NaN,JUANGUILLERMORUIZGUISAO
16,18,2023215026,JESUS DAVID VARELA MONTERO,NaN,JESUSDAVIDVARELAMONTERO

In [2]:
fecha="04-04-2025"
asistencia= pd.read_csv("C:\\Users\\User\\Downloads\\ControlAsistencia\\Viernes\\"+fecha+".csv",sep="\t",encoding="UTF-16")
asistencia['Nombre1']=asistencia['Nombre completo'].str.replace(" ","")
display(asistencia)

,Nombre completo,Acción del usuario,Marca de tiempo,Nombre1
0,Daniel Gonzalez Polo,Unido,NaN,DanielGonzalezPolo
1,JORGE ANDRES LARA AGUILAR,Unido,NaN,JORGEANDRESLARAAGUILAR
2,JORGE ANDRES LARA AGUILAR,Abandonó,NaN,JORGEANDRESLARAAGUILAR
3,JESUS DAVID VARELA MONTERO,Unido,NaN,JESUSDAVIDVARELAMONTERO
4,ANDY YULIETH BOLANO SILVA,Unido,NaN,ANDYYULIETHBOLANOSILVA
5,ANDY YULIETH BOLANO SILVA,Abandonó,NaN,ANDYYULIETHBOLANOSILVA
6,ANDY YULIETH BOLANO SILVA,Unido,NaN,ANDYYULIETHBOLANOSILVA
7,ANDY YULIETH BOLANO SILVA,Abandonó,NaN,ANDYYULIETHBOLANOSILVA
8,ANDY YULIETH BOLANO SILVA,Unido,NaN,ANDYYULIETHBOLANOSILVA
9,ANDY YULIETH BOLANO SILVA,Abandonó,NaN,ANDYYULIETHBOLANOSILVA
10,ANDY YULIETH BOLANO SILVA,Unido,NaN,ANDYYULIETHBOLANOSILVA
11,FAIRUZ TATIANA NUNEZ BENAVIDES,Unido,NaN,FAIRUZTATIANANUNEZBENAVIDES
12,NATALIA MARIA MACHADO MARTINEZ,Unido,NaN,NATALIAMARIAMACHADOMARTINEZ
13,SERGIO ANDRES MORALES MERCADO,Unido,NaN,SERGIOANDRESMORALESMERCADO
14,SERGIO ANDRES MORALES MERCADO,Abandonó,NaN,SERGIOANDRESMORALESMERCADO
15,SERGIO ANDRES MORALES MERCADO,Unido,NaN,SERGIOANDRESMORALESMERCADO
16,DANIELA MARSELA BOLANO TORRES,Unido,NaN,DANIELAMARSELABOLANOTORRES
17,SAMUEL DAVID GUERRA VEGA,Unido,NaN,SAMUELDAVIDGUERRAVEGA
18,SAMUEL DAVID GUERRA VEGA,Abandonó,NaN,SAMUELDAVIDGUERRAVEGA
19,SAMUEL DAVID GUERRA VEGA,Unido,NaN,SAMUELDAVIDGUERRAVEGA
20,KALETH RAFAEL PACHECO GARCIA,Unido,NaN,KALETHRAFAELPACHECOGARCIA
21,MAICOL GUILLERMO ASCANIO SILVA,Unido,NaN,MAICOLGUILLERMOASCANIOSILVA
22,JAIR ALBERTO REYES ELIAS,Unido,NaN,JAIRALBERTOREYESELIAS
23,JAIR ALBERTO REYES ELIAS,Abandonó,NaN,JAIRALBERTOREYESELIAS
24,JAIR ALBERTO REYES ELIAS,Unido,NaN,JAIRALBERTOREYESELIAS
25,LORENZO RAFAEL ROMERO FONSECA,Unido,NaN,LORENZORAFAELROMEROFONSECA
26,LORENZO RAFAEL ROMERO FONSECA,Abandonó,NaN,LORENZORAFAELROMEROFONSECA
27,JUAN JOSE RIVERA MERCHAN,Unido,NaN,JUANJOSERIVERAMERCHAN
28,JUAN JOSE RIVERA MERCHAN,Abandonó,NaN,JUANJOSERIVERAMERCHAN
29,JUAN JOSE RIVERA MERCHAN,Unido,NaN,JUANJOSERIVERAMERCHAN
30,JUAN JOSE RIVERA MERCHAN,Abandonó,NaN,JUANJOSERIVERAMERCHAN
31,JUAN GUILLERMO RUIZ GUISAO,Unido,NaN,JUANGUILLERMORUIZGUISAO
32,JUAN GUILLERMO RUIZ GUISAO,Abandonó,NaN,JUANGUILLERMORUIZGUISAO
33,VICTOR HUGO PATINO ZAMBRANO,Unido,NaN,VICTORHUGOPATINOZAMBRANO
34,LUIS MIGUEL BECERRA DIAZ,Unido,NaN,LUISMIGUELBECERRADIAZ
35,LUIS MIGUEL BECERRA DIAZ,Abandonó,NaN,LUISMIGUELBECERRADIAZ
36,LUIS MIGUEL BECERRA DIAZ,Unido,NaN,LUISMIGUELBECERRADIAZ
37,ANA VANESSA MADRID PEREZ,Unido,NaN,ANAVANESSAMADRIDPEREZ
38,ANA VANESSA MADRID PEREZ,Abandonó,NaN,ANAVANESSAMADRIDPEREZ
39,ANA VANESSA MADRID PEREZ,Unido,NaN,ANAVANESSAMADRIDPEREZ
40,ANA VANESSA MADRID PEREZ,Abandonó,NaN,ANAVANESSAMADRIDPEREZ
41,ANA VANESSA MADRID PEREZ,Unido,NaN,ANAVANESSAMADRIDPEREZ

## Control asistencia

## Verificar Asistencia

In [3]:
asistenciaNoRepetida=asistencia["Nombre1"].unique()

asistio = set()
noAsistio=[]
for nses, n in   zip(matriculados["NombreSinEspacios"],matriculados["Nombre"]):    
    if nses in asistenciaNoRepetida:
        asistio.add(n) 
    else:
        noAsistio.append(n)   
    

print("\n Asistió.........\n")
for e in asistio:
    print(e)

print("\n------------No Asisitió-------------- ")
for na in noAsistio:
    print(na)

 Asistió.........

MAICOL GUILLERMO ASCANIO SILVA
JORGE ANDRES LARA AGUILAR
 SERGIO ANDRES MORALES MERCADO
FAIRUZ TATIANA NUNEZ BENAVIDES
ANDY YULIETH BOLANO  SILVA
NATALIA MARIA MACHADO MARTINEZ
 KALETH RAFAEL PACHECO GARCIA
DANIELA MARSELA BOLANO TORRES
JUAN GUILLERMO RUIZ GUISAO
ANA VANESSA MADRID PEREZ
VICTOR HUGO PATINO ZAMBRANO
JUAN JOSE RIVERA MERCHAN
JESUS DAVID VARELA MONTERO
LORENZO RAFAEL ROMERO FONSECA
SAMUEL DAVID GUERRA VEGA
LUIS MIGUEL BECERRA DIAZ
JAIR ALBERTO REYES ELIAS

------------No Asisitió--------------

## Genera Archivo de Inasistencia

In [4]:
dfInasistencia = pd.DataFrame(noAsistio, columns=['Nombre Estudiante'])
dfInasistencia["Fecha"]=fecha

Inasistencia= pd.read_excel("C:\\Users\\User\\Downloads\\ControlAsistencia\\Viernes\\InasistenciaViernes.xlsx") 
frames = [Inasistencia,dfInasistencia]
result = pd.concat(frames)
result.to_excel("C:\\Users\\User\\Downloads\\ControlAsistencia\\Viernes\\InasistenciaViernes.xlsx",index=False)
print(result)

                Nombre Estudiante       Fecha
0       JAIR ALBERTO REYES ELIAS   07-02-2025
1       JUAN JOSE RIVERA MERCHAN   28-02-2025
2   SERGIO ANDRES MORALES MERCADO  21-03-2025